version: '2'
services:
    rabbit-mq:
        container_name: rabbit-mq
        image: rabbitmq:3
        expose:
            - 5672
        networks:
            - event-driven-spring-boot-network
        logging:
            driver: json-file
    rabbit_mq_receiver:
        container_name: rabbit_mq_receiver
        build:
            context: RabbitMQReceiver
            dockerfile: Dockerfile
        image: rabbit_mq_receiver:latest
        expose:
            - 8081
        ports:
            - "8081:8081"
        networks:
            - event-driven-spring-boot-network
        depends_on:
            - rabbit-mq
        links:
            - rabbit-mq:rabbit-mq
        logging:
            driver: json-file
    rabbit_mq_sender:
        container_name: rabbit_mq_sender
        build:
            context: RabbitMQSender
            dockerfile: Dockerfile
        image: rabbit_mq_sender:latest
        expose:
            - 8082
        ports:
            - "8082:8082"
        networks:
            - event-driven-spring-boot-network
        depends_on:
            - rabbit-mq
        links:
            - rabbit-mq:rabbit-mq
        logging:
            driver: json-file
networks:
    event-driven-spring-boot-network:
        driver: bridge